### ISSUE TITLE
Replacing an existing audio doesn't replace the existing idsp or lopus

### ISSUE THREAD

**Issue by junetried** [junetried/simple-nus3audio-gui#7]
What works:
- Imported audio is decoded, and playback works as expected
- Adding audio to **an empty item**

What doesn't work:
- Replacing audio which **is not empty**

**Comment by junetried** [comment]
Despite not replacing any audio, idsp items are incorrectly saved as lopus.

**Comment by junetried** [comment]
It's possible to work around this: after replacing the audio, change the format of the audio to IDSP or LOPUS and then back. This will get rid of the encoded audio in memory and force it to reencode from the imported audio, like it should be doing.

**Comment by coatlessali** [comment]
Can confirm this works. Thanks for getting on the problem so quickly.

**Comment by junetried** [comment]
Fixed with [v0.5.2](https://github.com/junetried/simple-nus3audio-gui/releases/tag/v0.5.2).
